export const ADD_A_LIST = 'ADD_A_LIST'
export const REMOVE_A_LIST = 'REMOVE_A_LIST'
export const ADD_A_ITEM = 'ADD_A_ITEM'
export const DELETE_A_ITEM  = 'DELETE_A_ITEM'
export const RENAME_LIST = 'RENAME_LIST'